version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: control_presencia_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootPass123!
      MYSQL_DATABASE: control_presencia
      MYSQL_USER: appuser
      MYSQL_PASSWORD: AppPass123!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local

